name: FTP Deploy

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # or use a newer version if available

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0  # or use a newer version if available
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html  # Adjust this path based on your Hostinger directory structure
